version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: embedding_api
    command: /start
    ports:
      - 9000:8000
    env_file:
      - .env
    volumes:
      - .:/app:z